### ISSUE TITLE
Use PHP namespaces to avoid conflicts

### ISSUE THREAD

**Issue by kouinkouin** [ShaneMcC/phprouter#16]
Hi,

I use your lib for some months, and that works fine (for telnet), thanks!

Is there objection to use namespaces in our library?
That will permit to avoid conflicts with others libs and sometimes PHP itself (5db83aabade55d1aa0efbd85a88c082c420421bc).

I can create a PR if you prefer, but I need a namespace to put (`ShaneMcC\PhpRouter` ?)

Of course, that will make break change, but it's simple to change (add namespace on hte class *Router and the rest works).

What do you think about that?

**Comment by ShaneMcC** [comment]
Hi,

I'd be perfectly fine with this.

I was planning on doing it when I did d0c264c2bc5908d29371ce3342d4bcbb74191a80 but didn't get round to it, and then when I did 5db83aabade55d1aa0efbd85a88c082c420421bc I needed a quick fix at the time.

I'd use `shanemcc\phprouter` (all lower-case) for the namespace name.

Thanks!

- Shane
