### ISSUE TITLE
Fail to connect

### ISSUE THREAD

**Issue by CharlyBote** [ShaneMcC/phprouter#21]
When I try to use the software to connect to Cisco Router, I receive this error.
`
Fatal error: Uncaught Error: Class 'CiscoRouter' not found in D:\xampp\htdocs\test.php:16 Stack trace: #0 {main} thrown in D:\xampp\htdocs\test.php on line 16`

The Code
`<?php

	include('PHPRouter.php');
	
	$router = new CiscoRouter('192.168.1.1', 'admin', 'password','telnet');
	$router->connect();
	$router->enable('enable');
	$config = $router->exec('show run');
	$router->disconnect();

	echo $config;    
?>`
Floders structure

> XAMPP

        |->htdocs
             |->Sockets
             |->thirdparty
             |->Implementations
             |->PHPRouter.php

any Ideas?

**Comment by ShaneMcC** [comment]
Hi,

A recent commit (https://github.com/ShaneMcC/phprouter/commit/810d4f0e1e2fb9626ef90273eb67edaf46cbec33) changed this to use namespaces, so you'll need to either use an autoloader like composer add `use ShaneMcC\PhpRouter\Implementations\CiscoRouter` near the top of the script.

- Shane
