### ISSUE TITLE
Telnet Access Error

### ISSUE THREAD

**Issue by CharlyBote** [ShaneMcC/phprouter#22]
Hi Again.
When I try to access the router via telnet, I get this error.

`Warning:` array_key_exists() expects parameter 2 to be array, null given in D:\CharlyBrown\Escritorio\MEGA\PHP\mktkAdmin\thirdparty\net_telnet\Net\Telnet.php on line 100

`Fatal` error: Uncaught Exception: unknown TELNET command: 253 in D:\CharlyBrown\Escritorio\MEGA\PHP\mktkAdmin\thirdparty\net_telnet\Net\Telnet.php:768 Stack trace: #0 D:\CharlyBrown\Escritorio\MEGA\PHP\mktkAdmin\thirdparty\net_telnet\Net\Telnet.php(738): Net_Telnet->send_telcmd('\xFD', '\x01') #1 D:\CharlyBrown\Escritorio\MEGA\PHP\mktkAdmin\thirdparty\net_telnet\Net\Telnet.php(642): Net_Telnet->initial_options() #2 D:\CharlyBrown\Escritorio\MEGA\PHP\mktkAdmin\Sockets\TelnetSocket.php(27): Net_Telnet->connect() #3 D:\CharlyBrown\Escritorio\MEGA\PHP\mktkAdmin\Implementations\CiscoTrait.php(33): shanemcc\PhpRouter\Sockets\TelnetSocket->connect() #4 D:\CharlyBrown\Escritorio\MEGA\PHP\mktkAdmin\test.php(8): shanemcc\PhpRouter\Implementations\CiscoRouter->connect() #5 {main} thrown in D:\CharlyBrown\Escritorio\MEGA\PHP\mktkAdmin\thirdparty\net_telnet\Net\Telnet.php on line 768`

thanks!

**Comment by ShaneMcC** [comment]
Hi,

What version of PHP?

Honestly not sure if this actually works under windows - if you don't have a linux box, maybe try using WSL?

**Comment by CharlyBote** [comment]
My PHP Version is 7.4.20
ok. I will try in my linux machine.
It's any way to access to other devices? like OLTs or other routers vendors?

Thanks!

**Comment by ShaneMcC** [comment]
I can only confirm it works with kit I have access to.

In theory it should be possible to extend it to other things but I can't really help.

**Comment by CharlyBote** [comment]
I receive the same error in linux.


[Sun Sep 05 23:28:54.434233 2021] [php7:warn] [pid 7033] [client 192.168.11.200:49671] PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/buscacli/thirdparty/net_telnet/Net/Telnet.php on line 100
[Sun Sep 05 23:28:54.434277 2021] [php7:error] [pid 7033] [client 192.168.11.200:49671] PHP Fatal error:  Uncaught Exception: unknown TELNET command: 253 in /var/www/buscacli/thirdparty/net_telnet/Net/Telnet.php:768\nStack trace:\n#0 /var/www/buscacli/thirdparty/net_telnet/Net/Telnet.php(738): Net_Telnet->send_telcmd('\\xFD', '\\x01')\n#1 /var/www/buscacli/thirdparty/net_telnet/Net/Telnet.php(642): Net_Telnet->initial_options()\n#2 /var/www/buscacli/Sockets/TelnetSocket.php(27): Net_Telnet->connect()\n#3 /var/www/buscacli/Implementations/CiscoTrait.php(33): shanemcc\\PhpRouter\\Sockets\\TelnetSocket->connect()\n#4 /var/www/buscacli/test.php(9): shanemcc\\PhpRouter\\Implementations\\CiscoRouter->connect()\n#5 {main}\n  thrown in /var/www/buscacli/thirdparty/net_telnet/Net/Telnet.php on line 768
